services:
  - type: web
    name: hotwheels-backend
    env: node
    rootDir: site_back
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000